#include <iostream>
#include <thread>
#include <random>
#include "bot4.hpp"
#include "bot5.hpp"
#include "chess.hpp"
#include "thread_pool.hpp"

const int N_GAMES = 300;
const std::string fen = STARTING_FEN;

const int N_THREADS = std::thread::hardware_concurrency() - 2;
const int N_GAMES_PER_THREAD = N_GAMES / N_THREADS;

// stats for each color
std::array<int, 2> wins = {0, 0};
std::array<int, 2> draws = {0, 0};
std::array<int, 2> losses = {0, 0};

bool random_bool() {
    // Create a random number generator
    std::random_device rd;
    std::mt19937 gen(rd());
    // Create a uniform distribution for 0 and 1
    std::uniform_int_distribution<> dis(0, 1);
    // Generate a random number between 0 and 1
    return dis(gen);
}

std::tuple<int, Color> match(int id) {
    int return_value = 0;
    Bot4_space::Bot4 bot1 = Bot4_space::Bot4(fen, random_bool());
    Bot5_space::Bot5 bot2 = Bot5_space::Bot5(fen, !bot1.color);

    while (!bot1.board.is_game_over()) {
        Move move;
        if (bot1.board.turn == bot1.color) {
            move = bot1.get_move();
        } else {
            move = bot2.get_move();
        }
        if (!move)
            throw std::runtime_error("Invalid move generated by bot");
        bot1.board.push(move);
        bot2.board.push(move);
    }

    std::string result = bot1.board.result();
    if ((result == "1-0" && bot1.color == WHITE) || (result == "0-1" && bot1.color == BLACK))
        return_value = 1;
    else if ((result == "1-0" && bot1.color == BLACK) || (result == "0-1" && bot1.color == WHITE))
        return_value = -1;
    else if (result == "1/2-1/2")
        return_value = 0;
    else
        fprintf(stderr, "Error: Invalid result %s\n", result.c_str());

    printf("Game %d (%s): %d\n", id, bot1.color ? "White" : "Black", return_value);
    return std::make_tuple(return_value, bot1.color);
}

int main() {
    std::cout << "Starting " << N_GAMES << " games...\n";
    std::vector<std::thread> threads;
    std::vector<std::tuple<int, Color>> results;

    ThreadPool pool(N_THREADS);
    printf("Thread pool created with %llu threads\n", pool.get_num_threads());
    for (int i = 0; i < N_GAMES; ++i) {
        pool.enqueue([&, i](int thread_id) {
            results.push_back(match(i));
        });
    }

/*
    for (int i = 0; i < N_THREADS; ++i) {
        threads.emplace_back([&, i]() {
            for (int j = 0; j < N_GAMES_PER_THREAD; ++j) {
                int game_id = i * N_GAMES_PER_THREAD + j;
                results[game_id] = match(game_id);
            }
        });
    }

    for (auto& thread : threads) {
        thread.join();
    }
*/
    pool.wait();

    for (const auto& result : results) {
        int res = std::get<0>(result);
        if (res == 1) {
            wins[std::get<1>(result)]++;
        } else if (res == -1) {
            losses[std::get<1>(result)]++;
        } else if (res == 0) {
            draws[std::get<1>(result)]++;
        } else {
            fprintf(stderr, "Error: Invalid result %d\n", res);
        }
    }

    int tot_white = wins[WHITE] + losses[WHITE] + draws[WHITE];
    int tot_black = wins[BLACK] + losses[BLACK] + draws[BLACK];
    std::cout << "\n----- Stats(Bot1 White) -----\n";
    std::cout << "Bot1 wins: " << wins[WHITE] << " (" << (wins[WHITE] * 100.0 / tot_white) << "%)\n";
    std::cout << "Bot1 draws: " << draws[WHITE] << " (" << (draws[WHITE] * 100.0 / tot_white) << "%)\n";
    std::cout << "Bot1 losses: " << losses[WHITE] << " (" << (losses[WHITE] * 100.0 / tot_white) << "%)\n";

    std::cout << "\n----- Stats(Bot1 Black) -----\n";
    std::cout << "Bot1 wins: " << wins[BLACK] << " (" << (wins[BLACK] * 100.0 / tot_black) << "%)\n";
    std::cout << "Bot1 draws: " << draws[BLACK] << " (" << (draws[BLACK] * 100.0 / tot_black) << "%)\n";
    std::cout << "Bot1 losses: " << losses[BLACK] << " (" << (losses[BLACK] * 100.0 / tot_black) << "%)\n";

    std::cout << "\n----- Overall Stats -----\n";
    std::cout << "Bot1 wins: " << wins[WHITE] + wins[BLACK] << " (" << ((wins[WHITE] + wins[BLACK]) * 100.0 / N_GAMES) << "%)\n";
    std::cout << "Bot1 draws: " << draws[WHITE] + draws[BLACK] << " (" << ((draws[WHITE] + draws[BLACK]) * 100.0 / N_GAMES) << "%)\n";
    std::cout << "Bot1 losses: " << losses[WHITE] + losses[BLACK] << " (" << ((losses[WHITE] + losses[BLACK]) * 100.0 / N_GAMES) << "%)\n";

    return 0;
}
